export const appStyles = {
  root: { minHeight: "100vh", background: "#0F172A", paddingBottom: 100 },
  container: { maxWidth: 480, margin: "0 auto", padding: "24px 16px 0" },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  logo: {
    fontSize: 22,
    fontWeight: 700,
    color: "#F1F5F9",
    letterSpacing: "-0.5px",
  },
  sub: { fontSize: 12, color: "#475569", marginTop: 2 },
  budgetChip: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 1,
    background: "#1E293B",
    border: "1px solid #334155",
    borderRadius: 10,
    padding: "8px 12px",
    cursor: "pointer",
  },
  budgetBar: { marginBottom: 12 },
  track: {
    height: 6,
    background: "#1E293B",
    borderRadius: 4,
    overflow: "hidden",
  },
  debtBanner: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "#78350F33",
    border: "1px solid #92400E",
    borderRadius: 10,
    padding: "10px 14px",
    marginBottom: 14,
  },
  monthNav: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  navBtn: {
    background: "none",
    border: "none",
    color: "#475569",
    fontSize: 20,
    cursor: "pointer",
    padding: "0 8px",
  },
  statsRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    background: "#1E293B",
    borderRadius: 12,
    padding: "14px 16px",
    marginTop: 14,
    border: "1px solid #334155",
  },
  stat: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
  },
  statVal: { fontSize: 14, fontWeight: 700, color: "#F1F5F9" },
  statLbl: {
    fontSize: 10,
    color: "#475569",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  statDivider: { width: 1, height: 28, background: "#334155" },
  insightBtn: {
    background: "none",
    border: "1px solid #334155",
    borderRadius: 8,
    padding: "6px 12px",
    fontSize: 12,
    color: "#60A5FA",
    fontWeight: 600,
    cursor: "pointer",
  },
  insightsCard: {
    background: "#1E293B",
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
    border: "1px solid #334155",
  },
  fab: {
    position: "fixed",
    bottom: 28,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: "50%",
    background: "linear-gradient(135deg, #3B82F6, #1D4ED8)",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 4px 24px rgba(59,130,246,0.4)",
  },
};
