export const appStyles = {
  root: { minHeight: "100vh", background: "#000", paddingBottom: 90 },
  container: { maxWidth: 480, margin: "0 auto", padding: "16px 16px 0" },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingTop: 8,
  },
  logo: {
    fontSize: 24,
    fontWeight: 700,
    color: "#fff",
    letterSpacing: "-0.5px",
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "linear-gradient(135deg,#F97316,#EC4899,#8B5CF6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInner: {
    width: 27,
    height: 27,
    borderRadius: "50%",
    background: "#000",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 700,
    color: "#fff",
  },
  monthStrip: {
    display: "flex",
    gap: 12,
    overflowX: "auto",
    marginBottom: 20,
    padding: "2px 0",
  },
  monthItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    flexShrink: 0,
    cursor: "pointer",
  },
  monthRingActive: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: "linear-gradient(135deg,#F97316,#EC4899,#8B5CF6)",
    padding: 2.5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  monthRingInactive: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: "#111",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  monthRingHasExp: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: "linear-gradient(135deg,#F97316,#EC4899)",
    padding: 2,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  monthInnerActive: {
    width: "100%",
    height: "100%",
    borderRadius: "50%",
    background: "#000",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    fontWeight: 700,
    color: "#fff",
  },
  monthInnerInactive: {
    width: "100%",
    height: "100%",
    borderRadius: "50%",
    background: "#111",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    fontWeight: 500,
    color: "#444",
  },
  statsRow: {
    display: "flex",
    justifyContent: "space-between",
    padding: "14px 0",
    borderTop: "0.5px solid #111",
  },
  stat: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
  },
  statVal: { fontSize: 20, fontWeight: 700, color: "#fff" },
  statLbl: {
    fontSize: 9,
    color: "#444",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  insightsCard: {
    background: "#0A0A0A",
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
    border: "1px solid #1A1A1A",
  },
  bottomBar: {
    position: "fixed",
    bottom: 0,
    left: 0,
    right: 0,
    background: "#000",
    borderTop: "0.5px solid #111",
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    padding: "12px 24px 28px",
    zIndex: 100,
  },
  tabBtn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    background: "none",
    border: "none",
    cursor: "pointer",
  },
  tabDot: { width: 4, height: 4, borderRadius: "50%", background: "#F97316" },
  fabBtn: {
    width: 58,
    height: 58,
    borderRadius: "50%",
    background: "linear-gradient(135deg,#F97316,#EC4899,#8B5CF6)",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 0 20px rgba(249,115,22,0.4)",
  },
  debtBanner: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "#78350F22",
    border: "1px solid #92400E",
    borderRadius: 10,
    padding: "10px 14px",
    marginBottom: 14,
  },
};
