export const calendarStyles = {
  grid: { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", gap: 3 },
  dayLabel: {
    fontSize: 10,
    color: "#3D3D3D",
    textAlign: "center",
    padding: "4px 0",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  cell: {
    background: "#252525",
    borderRadius: 8,
    padding: "6px 5px",
    minHeight: 68,
    display: "flex",
    flexDirection: "column",
    border: "1px solid #2A2A2A",
    transition: "border-color 0.1s",
  },
  thumb: { width: 22, height: 22, objectFit: "cover", borderRadius: 4 },
  moreChip: {
    width: 22,
    height: 22,
    borderRadius: 4,
    background: "#2E2E2E",
    color: "#6B7280",
    fontSize: 9,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  iconChip: {
    width: 20,
    height: 20,
    borderRadius: 4,
    fontSize: 11,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
};
