export const modalStyles = {
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.7)",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    zIndex: 1000,
    backdropFilter: "blur(4px)",
  },
  sheet: {
    background: "#1E1E1E",
    borderRadius: "20px 20px 0 0",
    width: "100%",
    maxWidth: 480,
    border: "1px solid #2A2A2A",
    borderBottom: "none",
    animation: "slideUp 0.25s ease",
  },
  handle: {
    width: 36,
    height: 4,
    background: "#2E2E2E",
    borderRadius: 2,
    margin: "12px auto 0",
  },
  sheetTitle: {
    fontSize: 17,
    fontWeight: 700,
    color: "#F1F5F9",
    textAlign: "center",
    padding: "16px 20px 4px",
  },
  sheetHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 20px",
    borderBottom: "1px solid #2A2A2A",
  },
  sheetTitle2: { fontSize: 15, fontWeight: 600, color: "#F1F5F9" },
  backBtn: {
    background: "none",
    border: "none",
    color: "#A3E635",
    fontSize: 14,
    cursor: "pointer",
    minWidth: 60,
  },
  bigBtn: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    background: "#252525",
    border: "1px solid #2A2A2A",
    borderRadius: 12,
    padding: "14px 16px",
    cursor: "pointer",
    textAlign: "left",
    width: "100%",
  },
  bigBtnIcon: { fontSize: 26, flexShrink: 0 },
  bigBtnLabel: {
    fontSize: 14,
    fontWeight: 600,
    color: "#F1F5F9",
    marginBottom: 2,
  },
  bigBtnSub: { fontSize: 12, color: "#4B5563" },
  photoZone: {
    border: "1.5px dashed #2A2A2A",
    borderRadius: 12,
    padding: "36px 20px",
    textAlign: "center",
    cursor: "pointer",
    background: "#252525",
    marginBottom: 14,
  },
  skipBtn: {
    width: "100%",
    background: "none",
    border: "1px solid #2A2A2A",
    borderRadius: 8,
    padding: "11px",
    fontSize: 13,
    color: "#4B5563",
    cursor: "pointer",
  },
  amountRow: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    marginBottom: 20,
    paddingBottom: 16,
    borderBottom: "1px solid #2A2A2A",
  },
  dollarSign: { fontSize: 30, fontWeight: 300, color: "#3D3D3D" },
  amountInput: {
    flex: 1,
    fontSize: 38,
    fontWeight: 700,
    color: "#F1F5F9",
    border: "none",
    outline: "none",
    background: "none",
    letterSpacing: "-0.5px",
  },
  input: {
    width: "100%",
    background: "#252525",
    border: "1px solid #2A2A2A",
    borderRadius: 8,
    padding: "10px 12px",
    fontSize: 13,
    color: "#F1F5F9",
    outline: "none",
  },
  friendBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 14px",
    borderRadius: 10,
    border: "1px solid #2A2A2A",
    background: "#252525",
    cursor: "pointer",
    marginBottom: 12,
    transition: "all 0.15s",
  },
  friendBoxOn: { background: "#A3E63511", borderColor: "#A3E635" },
  toggle: {
    width: 34,
    height: 20,
    borderRadius: 10,
    background: "#2E2E2E",
    position: "relative",
    transition: "background 0.2s",
    flexShrink: 0,
  },
  toggleOn: { background: "#A3E635" },
  thumb: {
    position: "absolute",
    top: 3,
    left: 3,
    width: 14,
    height: 14,
    borderRadius: "50%",
    background: "#fff",
    transition: "left 0.2s",
  },
  thumbOn: { left: 17 },
  removePhoto: {
    position: "absolute",
    top: 8,
    right: 8,
    background: "rgba(0,0,0,0.6)",
    border: "none",
    color: "#fff",
    borderRadius: "50%",
    width: 26,
    height: 26,
    cursor: "pointer",
    fontSize: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  error: {
    fontSize: 12,
    color: "#F87171",
    background: "#7F1D1D22",
    padding: "8px 12px",
    borderRadius: 7,
    marginBottom: 12,
    border: "1px solid #7F1D1D",
  },
  saveBtn: {
    width: "100%",
    background: "#A3E635",
    color: "#1E1E1E",
    border: "none",
    borderRadius: 12,
    padding: "14px",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    marginTop: 4,
  },
  scanSpinner: {
    width: 36,
    height: 36,
    borderRadius: "50%",
    border: "3px solid #252525",
    borderTopColor: "#A3E635",
    animation: "spin 0.8s linear infinite",
    margin: "0 auto",
  },
  daySheetRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: "12px 0",
    borderBottom: "1px solid #2A2A2A",
  },
  daySheetPhoto: {
    width: 52,
    height: 52,
    objectFit: "cover",
    borderRadius: 8,
    flexShrink: 0,
  },
  daySheetIconBox: {
    width: 52,
    height: 52,
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  settleBtn: {
    background: "#064E3B33",
    border: "1px solid #065F46",
    borderRadius: 6,
    padding: "4px 8px",
    fontSize: 11,
    color: "#34D399",
    cursor: "pointer",
    fontWeight: 600,
  },
  deleteBtn: {
    background: "#7F1D1D22",
    border: "1px solid #7F1D1D",
    borderRadius: 6,
    padding: "4px 6px",
    fontSize: 11,
    color: "#F87171",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
  },
};
