export const modalStyles = {
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.85)",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    zIndex: 1000,
    backdropFilter: "blur(8px)",
    touchAction: "none",
  },
  sheet: {
    background: "#0A0A0A",
    borderRadius: "20px 20px 0 0",
    width: "100%",
    maxWidth: 480,
    height: "92vh",
    display: "flex",
    flexDirection: "column",
    border: "1px solid #1A1A1A",
    borderBottom: "none",
    animation: "slideUp 0.25s ease",
  },
  handle: {
    width: 36,
    height: 4,
    background: "#222",
    borderRadius: 2,
    margin: "12px auto 0",
  },
  sheetHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 20px",
    borderBottom: "1px solid #1A1A1A",
  },
  sheetTitle2: { fontSize: 15, fontWeight: 600, color: "#fff" },
  backBtn: {
    background: "none",
    border: "none",
    color: "#F97316",
    fontSize: 14,
    cursor: "pointer",
    minWidth: 60,
  },
  amountRow: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    marginBottom: 20,
    paddingBottom: 16,
    borderBottom: "1px solid #1A1A1A",
  },
  dollarSign: { fontSize: 30, fontWeight: 300, color: "#222" },
  amountInput: {
    flex: 1,
    fontSize: 38,
    fontWeight: 700,
    color: "#fff",
    border: "none",
    outline: "none",
    background: "none",
    letterSpacing: "-0.5px",
  },
  input: {
    width: "100%",
    background: "#111",
    border: "1px solid #1A1A1A",
    borderRadius: 10,
    padding: "12px 14px",
    fontSize: 14,
    color: "#fff",
    outline: "none",
    fontFamily: "Inter, sans-serif",
    boxSizing: "border-box",
    display: "block",
  },
  error: {
    fontSize: 12,
    color: "#F87171",
    background: "#7F1D1D22",
    padding: "8px 12px",
    borderRadius: 7,
    marginBottom: 12,
    border: "1px solid #7F1D1D",
  },
  saveBtn: {
    width: "100%",
    background: "linear-gradient(135deg,#F97316,#EC4899,#8B5CF6)",
    color: "#fff",
    border: "none",
    borderRadius: 12,
    padding: "14px",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    marginTop: 4,
  },
  scanSpinner: {
    width: 36,
    height: 36,
    borderRadius: "50%",
    border: "3px solid #111",
    borderTopColor: "#F97316",
    animation: "spin 0.8s linear infinite",
    margin: "0 auto",
  },
};
